# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'pythonsample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

# - script: |
#     python -m pip install --upgrade pip setuptools wheel django
#     pip install -r requirements.txt
#     pip install unittest-xml-reporting
#   displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    python server/opensourcelist.py --no-input
  condition: succeededOrFailed()
  displayName: 'Run tests'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: "**/TEST-*.xml"
#     testRunTitle: 'Python $(PYTHON_VERSION)'

  